Repository icure/icure-kraken-oss, pull requests merged in 2022-10, with the labels that each got.

#28 Fixed import bug on toList in CodeController
  src/main/kotlin/org/taktik/icure/services/external/rest/v1/controllers/core/CodeController.kt
Labels: bug

#29 Fixed ServiceByHcPartyTagCodeDateFilter
  src/main/kotlin/org/taktik/icure/domain/filter/impl/service/ServiceByHcPartyTagCodeDateFilter.kt
Labels: bug

#35 EHR-61 - Added latest as version filter in Code Controller
  src/main/kotlin/org/taktik/icure/asyncdao/CodeDAO.kt
  src/main/kotlin/org/taktik/icure/asyncdao/impl/CodeDAOImpl.kt
  src/main/kotlin/org/taktik/icure/services/external/rest/v1/controllers/core/CodeController.kt
  src/main/kotlin/org/taktik/icure/services/external/rest/v2/controllers/core/CodeController.kt
  src/test/kotlin/org/taktik/icure/asyncdao/CodeDAOTest.kt
  src/test/kotlin/org/taktik/icure/services/external/rest/v1/controllers/core/VersionFilterEndToEndTest.kt
  src/test/resources/org/taktik/icure/db/codes/region_codes.json
Labels: bug, enhancement

#41 Updated Readme after migration to Kotlin 1.7.20
  README.md
  readme/build_and_run_menu.png
  readme/ksp_tasks.png
Labels: documentation

#42 Fixed bean not found
  src/main/kotlin/org/taktik/icure/properties/ExternalServicesProperties.kt
Labels: bug

#43 Added watch for ksp output files
  build.gradle.kts
Labels: bug

#45 EHR-86 Added Lenient serializer for collections
  src/main/kotlin/org/taktik/icure/entities/HealthcareParty.kt
  src/main/kotlin/org/taktik/icure/handlers/JacksonLenientCollectionDeserializer.kt
Labels: bug
